version: "3.8"

services:
  backend:
    build:
      context: ./web/backend
    container_name: textonly-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://textonly-postgres:5432/textonly
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - textonly-network

  coturn:
    image: instrumentisto/coturn
    container_name: coturn-server
    restart: always
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "5349:5349/tcp"
    environment:
      - TURN_USER=demo
      - TURN_PASSWORD=demo1234
      - REALM=webrtc.local
    command:
      - --no-auth
      - --lt-cred-mech
      - --realm=webrtc.local
      - --log-file=stdout
      - --min-port=49152
      - --max-port=65535
      - --no-tls
      - --no-dtls
    volumes:
      - ./turn-server/turn_data:/var/lib/coturn
    networks:
      - textonly-network

  postgres:
    image: postgres:16
    container_name: textonly-postgres
    restart: always
    environment:
      POSTGRES_DB: textonly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - textonly-network

volumes:
  postgres_data:

networks:
  textonly-network:
